### ISSUE TITLE
Make service-worker load bible pages offline

### ISSUE THREAD

**Issue by derpmarine168** [DSpeckhals/bible.rs#18]
Please could you allow more pages than static files to load offline. A preferable caching strategy would be network-first, cache-network-race or a cache-then-update strategy.
An example cache-first ‘ferch’ function would be:
```js
self.addEventListener('fetch', function(e) {
  e.respondWith(
    caches.match(e.request).then(function(r) {
          console.log('[Service Worker] Fetching resource: '+e.request.url);
      return r || fetch(e.request).then(function(response) {
                return caches.open(cacheName).then(function(cache) {
          console.log('[Service Worker] Caching new resource: '+e.request.url);
          cache.put(e.request, response.clone());
          return response;
        });
      });
    })
  );
});
```
However, this would require ocasional clearing to keep data up-to-date and also something to prevent storage overflows from search api calls. 
See [mdn](https://developer.mozilla.org/en-US/docs/Web/Apps/Progressive/Offline_Service_workers) for some docs.

**Comment by DSpeckhals** [comment]
Thanks for the advice. I've implemented the logic as suggested in the attached PR.
