### ISSUE TITLE
Add cache-control headers to reduce server load

### ISSUE THREAD

**Issue by derpmarine168** [DSpeckhals/bible.rs#19]
![image](https://user-images.githubusercontent.com/28905212/52121300-14686500-2617-11e9-9885-a823937fd9dc.png)
Adding `cache-control` headers has the possibility to significantly increase performance on older browsers and poor network connections. Adding an hour to half an hour of caching on the search function can significantly reduce server load and adding an hour to half an hour of caching on other pages could also significantly increase perofmance, especialy for those that tend to flick back and fourth between pages.

**Comment by DSpeckhals** [comment]
I made a change to do this in the NGINX reverse proxy. Thanks for pointing this out!

**Comment by derpmarine168** [comment]
No problem!
