### ISSUE TITLE
Add Schema.org data using HTML microdata or JSON-LD

### ISSUE THREAD

**Issue by derpmarine168** [DSpeckhals/bible.rs#22]
Adding Schema.org data using HTML microdata or JSON-LD can increase compatability with some reader mode software and accessability software, and can increase SEO. See [google's page](https://developers.google.com/search/docs/guides/intro-structured-data) for more info.

**Comment by DSpeckhals** [comment]
Thank you for the suggestion. I've implemented this in the attached PR. #26.
