### ISSUE TITLE
Importer Option to feed data

### ISSUE THREAD

**Issue by passionate2023** [DSpeckhals/bible.rs#76]
Hi,

Is it possible to provide an importer option to feed the data ?
Is it possible to have the db supported flatfile of multiple flavors?

Thanks

**Comment by DSpeckhals** [comment]
Yes, both of these are possible, but I'm not currently working on implementing it. In several recent commits, I made the version and metadata dynamic (no longer hard-coded). You'd mainly need to adapt to the same SQLite database format, probably with migration files similar to those in this repository: https://github.com/DSpeckhals/bible.rs-migrations

I would encourage anyone who's interested to add translations, and I'll accept contributions. For the time being, though, I'm not going to work on this myself.

**Comment by passionate2023** [comment]
Great...That's fine...Assume i create my own bible and sermons in two different sql lite db format as you have....My problem is how to build and bundle is a problem in windows and mac..

Can you please atleast formulate or capture the steps in fresh windows and mac ? If you have mac, you can install windows via virual box freeware. if you have windows, you can get a $1 mac for an hour to complete the installation process for verficiation

Badly need the exact detail and i can get the DB for both bible and sermons in the language.

**Comment by DSpeckhals** [comment]
I'm on Arch Linux, and I'm not planning on spinning up a Windows 10 VM on it anytime soon. If you or someone else would like to contribute the steps once you know they work, then I'll definitely be thankful for the PR.

**Comment by passionate2023** [comment]
Is it possible to help me with the steps from scratch on a) how to create a docker image b) how to build the project c) how to run in Arch linux,  so that i will create a virtual box in my windows machine with Arch linux and give a try.....

Please let me know if you could help me with the steps in fresh Arch linux

**Comment by DSpeckhals** [comment]
Any Linux VM should be fine. It doesn't have to be Arch Linux. Once you're there, install Docker, build the image (explained and the README), and run the container (also in the README).

If you don't want to build the image, you can just pull it: `docker pull dspeckhals/bible.rs`
